site_name: MkDocs on Vercel
docs_dir: content

nav:
  - 'Home': index.md

theme:
  name: material
  custom_dir: mkdocs-overrides
  features:
    - instant
  palette:
    primary: white
    accent: indigo
  logo: https://user-images.githubusercontent.com/101152/81295258-701e6b00-9070-11ea-9fbc-3f7d0c07c6d3.png

extra_css:
  - mkdocs.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
