site_name: MkDocs on Vercel
docs_dir: content

nav:
  - 'Home': index.md

theme:
  name: material
  custom_dir: mkdocs-overrides
  features:
    - instant
  palette:
    primary: white
    accent: indigo

extra_css:
  - mkdocs.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
